//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twinvision.BolRetailerApi.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Twinvision.BolRetailerApi.Test.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;invoiceSpecification&quot;:[{&quot;id&quot;:&quot;7616222250#1021103894#TURNOVER&quot;,&quot;invoiceLineRef&quot;:&quot;4500022543921#TURNOVER&quot;,&quot;invoicedQuantity&quot;:{&quot;unitCode&quot;:&quot;ZZ&quot;,&quot;unitCodeListID&quot;:&quot;UNECERec20&quot;,&quot;value&quot;:3.00},&quot;lineExtensionAmount&quot;:{&quot;currencyID&quot;:&quot;EUR&quot;,&quot;value&quot;:104.94},&quot;taxTotal&quot;:{&quot;TaxAmount&quot;:{&quot;currencyID&quot;:&quot;EUR&quot;,&quot;value&quot;:0.00}},&quot;item&quot;:{&quot;Description&quot;:[{&quot;value&quot;:&quot;Verkoopprijs artikel(en), ontvangen van kopers en door bol.com door te storten&quot;}],&quot;Name&quot;:{&quot;value&quot;:&quot;TURNOVER&quot;},&quot;ClassifiedTaxCategory&quot;:[{&quot;ID&quot;:{&quot;schemeAgencyID&quot;:&quot;6&quot;,&quot;schemeID&quot;:&quot;U [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResourceSpecificationValue {
            get {
                return ResourceManager.GetString("ResourceSpecificationValue", resourceCulture);
            }
        }
    }
}
